account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # the login,logout,password_change,password_reset,password_change/done these url is django build in,if you don't write in here,no problem,these url works fine
    # post views
    # path('login/', views.user_login, name='login'),
    # Django built in authentication (no views model needed) which one is denoted by 'auth'
    # after successfully login the url is login and using build in registration/login.html template
    # login,logout,password_chang,password_change_done,password_reset,password_reset_done is django build in,there
    # no need to create view function,search template from templates/registration/url_name file
    path('login/', auth_views.LoginView.as_view(), name='login'), # Django build in class based authentication view
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), # use logout template
    path('', views.dashboard, name='dashboard'),
    # here using django built in authentication views for password change
    # passwordchangeview will handle the form to change the password
    path('password_change/', auth_views.PasswordChangeView.as_view(),name='password_change'),
    # passwordchangedoneview will display a success message after the user has successfully changed his password
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    # reset password url using django authentication
    path('password_reset/', auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    # alternative way to authentication url
    # path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

bookmarks_main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')), # for social site(fb,twitter)
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('',views.image_list,name='list'),
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',views.image_detail,name='detail'),
    path('like/',views.image_like,name='like'),
]

account/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/',
                              blank=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)


class Contact(models.Model):
    user_form = models.ForeignKey('auth.User',related_name='rel_from_set',on_delete=models.CASCADE) # foreignkey for the user that creates the relationship
    user_to = models.ForeignKey('auth.User',related_name='rel_to_set',on_delete=models.CASCADE) # foreignkey for the user being followed
    created = models.DateTimeField(auto_now_add=True,db_index=True)  # to store the time when the relationship was created,we use db_index=True to create a database index for the created field.This will improve query performance when ordering querysets by this field

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_form,self.user_to)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    # django also provides UserCreationForm (built in),which is similar to this class,which resides django.contrib.auth.forms
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email') # override username,first_name and email to models

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm): # this fields override from models
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib import messages


# here we use Django built in authentication Loginview so this method is not in used
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], # here check the username which one is store in database and cd['username'] which one is came from login form
                                         password=cd['password']) # cd means clean data from form, username and password came from login form,if check these condition then 'user' is true
            if user is not None: # user is not none means the user is in database
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated '\
                                        'successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


# login required checks whether the current user is authenticated,this login_required is mixin(django build in),without inherit from mixin any person enter into dashboard
@login_required
def dashboard(request):
    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard'})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # save the user object in database
            new_user.save()
            # create a user profile(user is the parameter of profile)
            Profile.objects.create(user=new_user) # here create a user profile object as a 'new_user', if i don't register then edit path will not work
            return render(request, 'account/register_done.html',
                                    {'new_user': new_user})
    else:
        user_form = UserRegistrationForm() # when using get method
    return render(request,'account/register.html',
                          {'user_form': user_form})

# for editing purpose,we ensure that the user is login or not,this works done by django automatically by usin mixin(login)
@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated '\
                                      'successfully')
        else:
            messages.error(request, 'Error updating your profile')

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})

account/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
   <div id ="header">
       <span class="logo" >Bookmarks</span>
       {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "dashboard" %}class="selected"{% endif %}>
               <a href="{% url "dashboard" %}">My dashboard</a>
            </li>

            <li {% if section == "images" %}class="selected"{% endif %}>
                <a href="{% url "images:list" %}">Images</a> <!--the namespace is 'images' we set bookmarks_main\urls.py file -->
            </li>

            <li {% if section == "people" %}class="selected"{% endif %}>
                <a href="#">People</a>
            </li>
        </ul>
       {% endif %}

       <span class="user">
           {% if request.user.is_authenticated %}
             Hello {{ request.user.first_name }},
             <a href="{% url "logout" %}">Logout</a>
           {% else %}
             <a href="{% url "login" %}">Log-in</a>
           {% endif %}
       </span>
   </div>

   {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
              {{ message | safe }}
                <a href="#" class="close">x</a>
            </li>
        {% endfor %}
    </ul>
   {% endif %}

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
<!--here using ajax and jquery in script,ajax is using for when you like an image then the like number automatically increment without loading the page -->
<!--we load the jQuery framework from google's CDN and add it to the static directory of your application -->
   <script>
    src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
   </script>
<!--in this script we using block content and endblock for that reason all others template can use it -->
<!--inside the script tag the first line is jquery function that takes a handler that is executed when the DOM(document object model) hierarchy has been fully constructed,DOM is created by the browser when a web page is loaded,
  including our code inside the function,we will make sure that all html elements we are going to interact with are loaded in the DOM,our code will only be executed once the DOM is ready.we created a template block called domready,in which templates that extend the base template will be able to include specific js-->
   <script src="https://cdn.jsdeliver.net/npm/js-cookie@2/src/js.cookie.min.js">
   </script> <!--load the js cookie plugin from a public CDN so that we can easily interact with cookies,it is lightweight js  -->

   <script>
   // this setup will apply to all AJAX requests performed with jQuery
    var csrftoken = Cookies.get('csrftoken'); // read the value of csrftoken cookie with Cookies.get()
    function csrfSafeMethod(method) { // define the function to check whether an HTTP method is safe,safe methods don't require csrf protection(GET,HEAD,OPTIONS,TRACE)
        // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({  // set up jQuery ajax request using $.ajaxSetup()
      beforeSend: function(xhr, settings) { // before each ajax request is performed,we check whether the request method is safe and the current request is not cross-domain
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);  // if the request is unsafe,we set the X-CSRFToken header with the value obtained from the cookie
        }
      }
    });

    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
   </script>

</body>
</html>