bookmarks_main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')), # for social site(fb,twitter)
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('',views.image_list,name='list'),
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',views.image_detail,name='detail'),
    path('like/',views.image_like,name='like'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    # foreign key because a user can post multiple images
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200,blank=True) # for making beautiful SEO-friendly URLs
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,db_index=True) # this datetime is automatically set when the object is created,we use db_index=True so that django creates an index in the database for this field
    # this many to many relationship because a user like multiple images and a images liked by multiple users
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, # add another field to the image model to store the users who like an image,use many to many relationship because a user might like multiple images and each image can be liked by multiple users
                                        related_name='images_liked',
                                        blank=True) # we use 'image.users_like.all() for all user in one image or 'users.images_liked.all()' for all images liked by a user where 'images_liked' is related name

    def __str__(self):
        return self.title

    def get_absolute_url(self): # this method use for detail view,the url for detail image needs the parameter id,slug
        return reverse('images:detail',args=[self.id,self.slug]) # using args so passing a list,if you use kwargs then you have to pass a dictionary

    def save(self, *args, **kwargs):
        # to automatically generate the slug field based on the value of the title field when no slug is provided
        # slugify function provided to automatically generate the image slug so that users don't have to manually enter a slug for each image
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image,self).save(*args, **kwargs)

images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image  # use the Image model and use these fields
        fields = ('title', 'url', 'description') # users will not enter the image URL directly in the form,we will provide them with a javascript tool choose an image from an external site and our form will receive it URL as a parameter
        widgets = {
            'url': forms.HiddenInput, # this widget because we don't want this field to be visible
        }

    def clean_url(self):
        url = self.cleaned_data['url']  # get the value of url field accessing cleaned_data dict. of the form instance
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower() # take extension of image,split the right side and take the extension(first element)
        if extension not in valid_extensions: # check the extension is jpg or jpeg format otherwise raise error
            raise forms.ValidationError('The given URL does not '\
                                        'match valid image extensions.')
        return url

    def save(self, force_insert=False, force_update=False, commit=True): # override the save method for saving purpose,if commit=False then save() method will return a model instance but will not save it to the database
        image = super(ImageCreateForm, self).save(commit=False) # create a new image instance from ImageCreateForm class and commit=False means don't save it to database
        image_url = self.cleaned_data['url']  # we get the url from the cleaned_data dict. of the form
        # generated the image name by combining the image title slug with the original file extension(jpg or jpeg)
        image_name = '{}.{}'.format(slugify(image.title), image_url.rsplit('.', 1)[1].lower())

        # download image from the given URL,use the python urllib module to download the image and
        response = request.urlopen(image_url)
        # passing it a contentfile object that is instantiated with the download file
        image.image.save(image_name, ContentFile(response.read()), save=False) # call the save() method of the image field,passing it a ContentFile obj that is instantiated with the downloaded file content. save = false means avoid the save in database yet
        if commit:  # now if the commit is true then save the image
            image.save()
        return image

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@login_required
def image_list(request):
    images = Image.objects.all() # we create a Queryset to return all images from the database
    paginator = Paginator(images,8) # we build a paginator object to paginate the results retrieving 8 images per page
    page = request.GET.get('page') # take the current page number
    try:
        images = paginator.page(page) # take the all images in current page and store it to 'images' variable
    except PageNotAnInteger:
        # if image is not an integer deliver the first page
        images = paginator.page(1)
    except EmptyPage: # we get an empty page exception if the requested page is out of range.If this is the case and requested is done via AJAX,we return an empty Httpresponse that will help us stop the AJAX pagination on the client side
        if request.is_ajax():
            # if the request is AJAX and the page is out of range,return an empty page
            return HttpResponse('')
        # if page is out of range deliver last page of results
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,'images/image/list_ajax.html',{'section':'images','images':images}) # for ajax requests,we render the list_ajax.html template,this template will only contain the images of the requested page
    return render(request,'images/image/list.html',{'section':'images','images':images}) # (else) we render the list.html template,this template will extend the base.html to display the whole page and will include the list_ajax.html template to include the list of images


@login_required # using this decorator to prevent access for unauthenticated users
def image_create(request):
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_item = form.save(commit=False) # create a instance of form class and store it to new_item variable,and don't save it to database yet
            # assign current user to the item
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Image added successfully')

            # redirect to new created item detail view
            return redirect(new_item.get_absolute_url()) # redirect the user to the canonical URL of new image
    else:
        # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    return render(request,
                  'images/image/create.html',
                  {'section': 'images',
                   'form': form})


def image_detail(request, id, slug): # take the parameter id,slug from urls
    image = get_object_or_404(Image,id=id,slug=slug) # find the current image using the parameter id,slug
    return render(request,'images/image/detail.html',{'section':'images','image':image})


@ajax_required # ajax required is custom file which one we create on common/decorators.py file which requires the ajax to see the 'image_like' function
@login_required  # the decorator prevents users that are not logged in from accessing this view
@require_POST  # this decorator returns an HttpResponseNotAllowed object,if the HTTP request is not done via POST,this way we only allow POST requests for this view
def image_like(request):
    image_id = request.POST.get('id') # the ID of the image object on which the user is performing the action
    action = request.POST.get('action')  # the action that the user wants to perform,which we assume to be a string with the value like or unlike
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user) # add the current user of 'Image' model in 'users_like' attribute,using add() or remove() methods
            else:
                image.users_like.remove(request.user) # remove the current user of 'Image' model in 'users like' attribute(using fk relationship)
            return JsonResponse({'status':'ok'})

        except:
            pass
    return JsonResponse({'status':'ko'}) # it is HTTP response with json content type,converting the given object into a JSON output

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Bookmark an image{% endblock %}

{% block content %}
  <h1>Bookmark an image</h1>
  <img src="{{ request.GET.url }}" class="image-preview">
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!">
  </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
  <h1>{{ image.title }}</h1>
   <!-- <img src="{{ image.image.url }}" class="image-detail"> --> <!--'image' is pass from views.py file which describe each image,and later 'image' is attribute of the model,show the url format  -->
    {% load thumbnail %}
    {% thumbnail image.image "300" as im %} <!--we define a thumbnail with a fixed width of 300 pixels,the first time a user loads this page,a thumbnail image will be created  -->
     <a href="{{ image.image.url }}">
         <img src="{{ im.url }}" class="image-detail"> <!--thumbnail image show as a 'im' -->
     </a>
    <!--sorl-thumbnail cropping algorithms and different effects that can be applied,if you have any difficulty generating thumbnails you can add THUMBNAIL_DEBUG = True -->
    {% endthumbnail %}


    {% with total_likes=images.users_like.count users_like=image.users_like.all %} <!--we make use of this tag to store the result of the Queryset,counting all user likes in a new variable called total_likes,we added another variable 'users_like' to the template tag in order to store the results of the image.users_like.all query -->
    <div class="image-info">
     <div>
        <span class="count">
            <span class="total"> {{ total_likes }} </span> <!--we display the total number of users that like this image and include a link to like/unlike the image -->
            like {{ total_likes|pluralize }} <!--ex: 12 likes -->
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button"> <!--if the current user is in 'users_like' means the user is already liked then show the 'un' option before the 'like',this means after click the 'like' button this button changes to 'unlike'(here acts as a action),the html code below there -->
            {% if request.user not in users_like %}
              Like
            {% else %}
              Unlike
            {% endif %}
        </a>
     </div>
     {{ image.description|linebreaks }}
    </div>
    <div class="image-likes">
        {% for user in image.users_like.all %} <!--iterate over all the users who like this image -->
          <div>
              <img src="{{ user.profile.photo.url }}"> <!--each user who like the image(using fk relationship),profile is the model of each user(account),photo is the attribute of profile model,and use the url,and the 'user' of Profile model is same as 'user' of Image model  -->
              <p>{{ user.first_name }}</p>
          </div>
        {% empty %}
          Nobody likes this image yet.
        {% endfor %}
    </div>
    {% endwith %}
{% endblock %}
<!--here call the AJAX view,passing the image ID and action parameters to it,AJAX request is successful update the data-action attribute of the <a> HTML element with the opposite action(like/unlike)  -->

{% block domready %}
    $('a.like').click(function(e){  // use 'a.like' jquery selector to find all elements of the html document with the like class,define a handler function for the click event,this function will be executed every time the user clicks on the like/unlike link
    e.preventDefault(); // to avoid the default behavior of the 'a' element
    $.post('{% url "images:like" %}', // use 'post' to perform an asynchronous POST request to the server and later use template tag to build the u r l for ajax request
    {
       id: $(this).data('id'), // we build the post parameters dictionary to send in the request,these are the ID and action parameters which is used in html file
       action: $(this).data('action')
    },
    function(data){  // we define a callback function that is executed when the HTTP response is received,it takes a data attribute that contains the content of the response
    if (data['status'] == 'ok') // we access the status attribute of the data received and check whether it equals ok,if the returned data is as expected,we toggle the data-action attribute of the link and its text
    {
      var previous_action = $('a.like').data('action'); // we increase or decrease the total like count by one,depending on the action performed
      // toggle data-action
      $('a.like').data('action', previous_action == 'like' ?
      'unlike' : 'like');
      // toggle link text
      $('a.like').text(previous_action == 'like' ? 'Unlike' :
      'Like');
      // update total likes
      var previous_likes = parseInt($('span.count .total').text());
      $('span.count .total').text(previous_action == 'like' ?
      previous_likes + 1 : previous_likes - 1);
    }
   }
  );
});
{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
        {% include "images/image/list_ajax.html" %} <!--to avoid repeating code,we included the list_ajax.html template for displaying images -->
    </div>
{% endblock %}
<!--the list.html template will hold the javascript code for loading additional pages when scrolling to the bottom of the page -->
<!--this code provides the infinite scroll functionality,we include the js code in the domready block that we defined in the base.html template -->
{% block domready %}
 var page = 1;   // stores the current page number
 var empty_page = false;  // allows us to know whether the user is on the last page and retrieves an empty,as soon as we get an empty page,we will stop sending additional ajax requests because we will assume that there are no more results
 var block_request = false; // prevents us from sending additional requests while an ajax request is in progress
 $(window).scroll(function() {  // we use it to capture the scroll event and also to define a handler function for it
   var margin = $(document).height() - $(window).height() - 200; // we calculate the margin variable to get the difference between the total document height and the window height,because thats the height of the remaining content for the user to scroll.we subtract a value of 200 from the result so that we load the next page when the user is closer than 200 pixels to the bottom of the page
   if ($(window).scrollTop() > margin && empty_page == false && // we only send an ajax request if no other ajax request is being done(block_request has to be false) and user didn't get to the last page of results (empty_page is also false)
   block_request == false) {
    block_request = true;  // we set block_request to true to avoid situation whereby the scroll event triggers additional ajax requests,and increase the page counter by one
     page += 1;
     $.get('?page=' + page, function(data) { // we perform an ajax get request and receive the html response in a variable called data
      if(data == '') {  // if the response has no content we got the end of the results,and there are no more pages to load,we set empty_page to true to prevent additional ajax requests
         empty_page = true;
      }
      else {
        block_request = false;  // if the response contain data we append the data to the html element with the image-list id,the page content expands vertically appending results when the user approaches the bottom of the page
        $('#image-list').append(data);
      }
    });
   }
 });
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %} <!--load the thumbanil for thumbnail type images -->

{% for image in images %} <!--images is pass from view/image_list -->
    <div class="image">
        <a href="{{ image.get_absolute_url }}"> <!-- create the link which describe detail view -->
         {% thumbnail image.image "300x300" crop="100%" as im %} <!--thumbnail image load as im(pixel is 300*300) -->
         <a href="{{ image.get_absolute_url }}">
             <img src="{{ im.url }}"> <!--show the u r l of image.image load as im  -->
         </a>
       {% endthumbnail %} <!--end the thumbanil image -->
    </a>
     <div class="info">
         <a href="{{ image.get_absolute.url }}" class="title">
             {{ image.title }}  <!--show the image title with detail view using get_absolute_url method -->
         </a>
     </div>
    </div>

{% endfor %}